name: macOS

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 6 * * *"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Install some packages
        run: ./test

      - name: Test package installed via brew directive
        run: brew ls ack

      - name: Test package installed via cask directive
        run: brew ls --cask gpg-suite

      - name: Test brew package installed via brewfile directive
        run: brew ls --cask firefox

      - name: Test cask package installed via brewfile directive
        run: brew ls jq
